### ISSUE TITLE
Deserializing BoxedSerialize

### ISSUE THREAD

**Issue by cryptoquick** [kardeiz/jsonrpc-v2#14]
We're using jsonrpc-v2 as a sort of transport-agnostic RPC server router and for server state management. I'm currently working on a tide and tide-websockets implementation. I'd like to take a ResponseObject and deserialize its BoxedSerialize data. Is there a good way to do that?

**Comment by kardeiz** [comment]
@cryptoquick There is an okay way to deserialize the `result` data:

```rust
let data = serde_json::from_value::<MyDeserializeType>(serde_json::to_value(result)?)?;
```

Despite the name, there is no intermediary JSON string or anything like that, though there could be some overhead generating unnecessary `BTreeMap`s, etc.

**Comment by cryptoquick** [comment]
That's perfect! That unblocks me, thank you. Anybody ever tell you, you're really good at Rust? Your code does stuff I didn't think was even possible in Rust. At first I didn't get it, but then I started digging in, and now I'm starting to appreciate the framework complexity, if it's so that the actual usage becomes less complex.

You could probably do with better docs, of course. I'd write some if I could. You've done an excellent job so far.

**Comment by kardeiz** [comment]
@cryptoquick I'm glad this fix worked for you. Thanks so much for the kind words!
