### ISSUE TITLE
Missing type extensions data on RequestBuilder-generated RequestObject

### ISSUE THREAD

**Issue by cryptoquick** [kardeiz/jsonrpc-v2#15]
I'm getting a `Missing data` `Internal Error` after passing a RequestObject made with RequestBuilder. I'm wondering if somehow Rust is losing track of the type of the data when being inserted into `extensions`.

If it helps any, this is my error response:

```
"{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32603,\"message\":\"Internal Error\",\"data\":\"Missing data for: rpc::data_types::RpcState<forest_db::rocks::RocksDb, key_management::keystore::PersistentKeyStore, beacon::drand::DrandBeacon>`\"},\"id\":0}"
```

I notice it omits the Arc, not sure if that's relevant, or if it's just stripped by the compiler because it's unnecessary in this context.

Also, I noticed that the version of `extensions` used by this library is a bit outdated, since you've renamed it to `type-map`.

**Comment by kardeiz** [comment]
@cryptoquick Are you sure your type `RpcState<RocksDb, PersistentKeyStore, DrandBeacon>` matches the exact type added with `Server::with_data`? Can you share the lines where you add it, and where you are attempting to extract it?

I really don't think it is the issue, but good call on `extensions` being outdated. I initially named it `extensions` since it was mostly just a non-actix-web version of actix-web's `Extensions`, but then realized it was more generally useful, so renamed it to `type-map`. I'll update it to use `type-map` in a future release.

**Comment by cryptoquick** [comment]
@kardeiz Yes, I added this:

`log::debug!("{}", std::any::type_name::<RpcState<DB, KS, B>>());`

And received this:

`rpc::data_types::RpcState<forest_db::rocks::RocksDb, key_management::keystore::PersistentKeyStore, beacon::drand::DrandBeacon>`

Here's where I provide the state struct to `with_data`: https://github.com/ChainSafe/forest/blob/8f3f5768d569192f678ff7314e30ed21ac15ca00/node/rpc/src/lib.rs#L54

Then I provide the entire RpcServer to Tide, because we want it to encapsulate our state in one place:
https://github.com/ChainSafe/forest/blob/8f3f5768d569192f678ff7314e30ed21ac15ca00/node/rpc/src/lib.rs#L238

And we get it back out of `tide` in the request here:
https://github.com/ChainSafe/forest/blob/8f3f5768d569192f678ff7314e30ed21ac15ca00/node/rpc/src/rpc_http_handler.rs#L44

And finally, handle is called here:
https://github.com/ChainSafe/forest/blob/8f3f5768d569192f678ff7314e30ed21ac15ca00/node/rpc/src/rpc_util.rs#L35

Not sure if this was the best way to do it, but it was the best way I could think of. Ideally there'd be a tide integration, but also, it wouldn't be as much use to me unless there was some form of streaming support, and I'm not sure a decent spec exists for JSON-RPC-style events over WS, like there is for [JSON-RPC over HTTP](https://www.jsonrpc.org/historical/json-rpc-over-http.html) (not implying that it's applicable to v2).

That said, if you'd like me to contribute in a way that produces a more ideal solution that might be more obvious to you, I'd certainly be willing to help!

**Comment by kardeiz** [comment]
Ahh, okay! Change your `with_data` call to:

```rust
with_data(Data(state))
```

`Data::new` will wrap your type with `Arc`, which is not necessary for your case, so you can construct it as above. That should resolve your issue.

With your current setup, it would be possible to extract the data in your handler like:

```rust
data: Data<Arc<RpcState<DB, KS, B>>>,
```

but the first way avoids the double `Arc`, so it should be preferred.

**Comment by cryptoquick** [comment]
That worked perfectly!!! Thank you!! I don't know who you are, but you write Rust on a level that is really, just, next-level. I would never have thought to try that. Not sure if you're looking for work, but we'd probably hire you in an instant, just sayin. You also make pallet, which is another cool thing that's come up in our company, for a distributed web browser and integrated P2P search engine we've been ideating on. Anyway, thank you, thank you so much. :pray:
