### ISSUE TITLE
Deserializing Response and Error Object

### ISSUE THREAD

**Issue by cryptoquick** [kardeiz/jsonrpc-v2#18]
One issue I'm having as I'm working on a client version for this is deserializing the error type.

It's not quite as simple as adding the Deserialize trait on the Error enum due to BoxedSerialize. There seems to be no Deserialize in erased_serde, for example. What do you suggest?

If it helps, I was using this earlier, but I'm not sure if it's a great solution:

```rust
/// Error object in a response
#[derive(Deserialize)]
struct JsonRpcError {
    pub code: i64,
    pub message: String,
}

impl fmt::Display for JsonRpcError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Error ({}): {}", self.code, self.message)
    }
}

#[derive(Deserialize)]
struct JsonRpcResponse<T> {
    pub jsonrpc: String,
    pub result: Option<T>,
    pub error: Option<JsonRpcError>,
    pub id: Option<Id>,
}
```

**Comment by kardeiz** [comment]
If you are creating an alternate `Error` object already, couldn't you just do:

```rust
#[derive(Deserialize)]
struct JsonRpcError<T> {
    pub code: i64,
    pub message: String,
    pub data: Option<T>,
}
```

Alternately, if you wanted to extract the `data` from a `jsonrpc_v2::Error`, you could use the `to_value/from_value` hack I describe in https://github.com/kardeiz/jsonrpc-v2/issues/14.

Also, I realize this is probably a work in progress, but the `result` and `error` options in `JsonRpcResponse` are not ideal. It would be better to put this in an enum to enforce the fact that there cannot be both a result and an error present (according to the JSONRPC 2.0 spec).

**Comment by cryptoquick** [comment]
That makes a lot of sense! It was really a hack just to get things to work. Thank you for being patient with me. It's always humbling, haha. I'll close this now.
