### ISSUE TITLE
Actix-identity support

### ISSUE THREAD

**Issue by kekcheburec** [kardeiz/jsonrpc-v2#3]

**Comment by kardeiz** [comment]
Sorry for the delay in responding. What kind of support are you looking for? Being able to extract `Identity` from the `jsonrpc_v2` `Request` object, or something more?

I think I might instead just look into providing the underlying `actix_web::HttpRequest` as extractable in the method handlers. It would then be possible to `actix_web::FromRequest::extract` the `Identity` (or anything else that implements `actix_web::FromRequest`) inside the handler.

This would be a little less convenient than being able to extract `Identity` directly. Would that work for you?

**Comment by kekcheburec** [comment]
Yes, I looked and realized that it would not be very convenient and it is worth changing the interaction with the server.
Thanks for the nice library.
