### ISSUE TITLE
Broken link to ErrorLike in readme

### ISSUE THREAD

**Issue by slyshykO** [kardeiz/jsonrpc-v2#4]
[`ErrorLike`](trait.ErrorLike.html) point to nothing.

**Comment by kardeiz** [comment]
Thanks for letting me know! It was working, but only when viewing the readme at https://docs.rs/jsonrpc-v2/. I've fixed the links for other places in [`0.5.1`](https://crates.io/crates/jsonrpc-v2/0.5.1).
